ENV: "swibrid"
SNAKEOPTS: "-j 100 -k --rerun-incomplete --latency-wait 60 -p --retries 10 --profile=cubi-dev" 
STUDY: "20240425_vincendeau_samples"
INPUT: ""
SAMPLE_SHEET: ""
SAMPLES: ["PRJNA831666_Shld1_1","PRJNA831666_Shld1_2","PRJNA831666_Shld1_3","PRJNA831666_Shld1_Xlf_1","PRJNA831666_Shld1_Xlf_2","PRJNA831666_Shld1_Xlf_3","PRJNA831666_WT_1","PRJNA831666_WT_2","PRJNA831666_WT_3","PRJNA831666_Xlf_1","PRJNA831666_Xlf_2","PRJNA831666_Xlf_3"]
#SAMPLES: ["20220425_BRCA1_4"]
BARCODES_PRIMERS: "../index/barcodes_primers.fa"
MINLENGTH: 500
LAST_INDEX: '../index/mm10db'
MINIMAP_INDEX: '../index/mm10-ont.mmi'
ALIGNER: "LAST"
REFERENCE: '../index/mm10.fa'
TELO_REPEAT: '../index/telomerSequence.fasta'
ANNOTATION: '../index/gencode.M12.annotation.exon.gene.shorted.bed'
SWITCH: 'chr12:113200000-113500000:-'
SWITCH_ANNOTATION: 'mm10_switch_regions.bed'
VARIANT_MAX_NREADS: 10000
NMAX: 50000
MAX_GAP: 75
BINSIZE: 50
BLACKLIST_REGIONS: ''
WEIGHTS: 'cluster'
CLUSTERING_METRIC: 'cosine'
CLUSTERING_METHOD: 'average'
CLUSTERING_CUTOFF: 0.01
CLUSTER_FILTERING_CUTOFF: 0.95
CLUSTER_DOWNSAMPLING_NREADS: 1000
CLUSTER_DOWNSAMPLING_NREPS: 10
